consumer: [MongoConsumer, LogConsumer, FileConsumer]
api:
  twitter:
    # Possible values for filters are location, terms so far
    filters: [location, terms]
    # [Southwest longitude, Southwest latitude, Northeast longitude, Northeast latitude]
    # That are the bounding box coordinates of Berlin
    locations:
      - [13.118362, 52.38482, 13.729477, 52.718827]
      - [13.118362, 52.38482, 13.729477, 52.718827]
    termsFile: ./config/terms.txt
    authType: OAuth
    auth:
      consumerKey: string
      consumerSecret: string
      token: string
      tokenSecret: string
database:
  mongo:
    host: localhost
    port: 27017
    database: broccoli
    collection: TweetsByTerms
  file: ./data/TweetsByTerms.txt

