api:
  twitter:
    termsFile: ./config/terms.txt
    authType: OAuth
    auth:
      consumerKey: string
      consumerSecret: string
      token: string
      tokenSecret: string
database:
  mongo:
    host: localhost
    port: 27017
    database: broccoli
    collection: TweetsByTerms
  file: ./data/TweetsByTerms.txt
